# Generated by Django 2.2 on 2023-01-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0003_auto_20230104_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='user',
            new_name='user_id',
        ),
    ]
