# Generated by Django 2.2 on 2023-01-04 09:45

from django.db import migrations, models
import profile_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0005_auto_20230104_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(blank=True, default='assests/home/user-icon.png', upload_to=profile_page.models.user_directory_path),
        ),
    ]
