# Generated by Django 2.2 on 2023-01-05 07:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profile_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0007_auto_20230104_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetails',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to=profile_page.models.user_video_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('video_title', models.TextField()),
                ('video_description', models.TextField(blank=True)),
                ('video_likes', models.BigIntegerField(default=0)),
                ('video_comments', models.BigIntegerField(default=0)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile_page.UserDetails')),
            ],
        ),
    ]
