# Generated by Django 2.2 on 2023-01-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0009_auto_20230105_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetails',
            name='video_category',
            field=models.CharField(default='Video', max_length=50),
        ),
        migrations.AddField(
            model_name='videodetails',
            name='video_views',
            field=models.BigIntegerField(default=0),
        ),
    ]
