# Generated by Django 2.2 on 2023-01-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0010_auto_20230106_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetails',
            name='video_category',
            field=models.CharField(max_length=50),
        ),
    ]
