# Generated by Django 2.2 on 2023-01-06 12:43

from django.db import migrations, models
import profile_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0013_auto_20230106_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetails',
            name='video_thumbnail',
            field=models.ImageField(default='thumbnail.png', upload_to=profile_page.models.user_thumbnail_directory),
        ),
    ]
