# Generated by Django 2.2 on 2023-01-10 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0014_videodetails_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='profile_page.UserDetails'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myfollowers', to='profile_page.UserDetails')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myfollowing', to='profile_page.UserDetails')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
