# Generated by Django 2.2 on 2023-01-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0016_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetails',
            name='video_dislikes',
            field=models.BigIntegerField(default=0),
        ),
    ]
