# Generated by Django 2.2 on 2023-01-10 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0015_auto_20230110_0532'),
        ('video_page', '0002_savedvideos_unsavedvideos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='profile_page.UserDetails')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenting_video', to='profile_page.VideoDetails')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
